### ISSUE TITLE
Problema al entrar cuando inicias sesión

### ISSUE THREAD

**Issue by daloru7844** [daloru7844/todo-php-m8-uf4#4]
Me sale un error al pasar los datos de inicio de sesión. Sospecho que el problema está aquí.
![image](https://user-images.githubusercontent.com/91331878/166839063-905c9319-7e57-43a8-beac-5c943159bb26.png)

**Comment by Daviddica** [comment]
El problema está en la sentencia cuando se llama al campo de la descripción, el campo debería llamarse como en la bd (desc) y no como está especificado (deskr)

**Comment by daloru7844** [comment]
Tienes razón, en el campo 'desc' estaba el error.

Gracias, David.
