### ISSUE TITLE
Error Variable de Sesión

### ISSUE THREAD

**Issue by MarcFiel1** [daloru7844/todo-php-m8-uf4#5]
Al iniciar sesión, la variable de sesión del email sale null. Me he dado cuenta haciendo el var_dump():

![image](https://user-images.githubusercontent.com/93161599/166944646-d5bd6f82-9666-4c0d-b84b-8c436a430e4e.png)

**Comment by alexarques** [comment]
Cierro la issue que ya lo ha arreglado @Daviddica 🙌
